/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_github_aaronr92_Main */

#ifndef _Included_io_github_aaronr92_Main
#define _Included_io_github_aaronr92_Main
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_github_aaronr92_Main
 * Method:    addNum
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_io_github_aaronr92_Main_addNum
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
